# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-15 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0003_targetword'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetword',
            name='datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
