# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-15 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0004_targetword_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
